language: minimal
if: branch = master

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only

script:
  - helm lint .
  - mkdir docs
  - echo $(pwd)
  - helm package . -d docs
  - cp README.md docs
  - cd docs
  - helm repo index .
  - ls -ltr 
  
deploy:
  provider: pages  
  github_token: $GITHUB_TOKEN
  local_dir: docs
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: master