apiVersion: v1
data:
  exported.yaml: LS0tCnR5cGU6IE5hbWVzcGFjZQphcGlfdmVyc2lvbjogY29yZS92MgptZXRhZGF0YToKICBuYW1lOiBkZXZlbG9wbWVudApzcGVjOgogIG5hbWU6IGRldmVsb3BtZW50Cg==
kind: Secret
metadata:
  creationTimestamp: null
  name: exported
  namespace: sensu
