apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.sensuStatefulSetName }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "sensu-go-statefulset.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Values.serviceHeadless.name }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sensu-go-statefulset.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sensu-go-statefulset.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 30
      initContainers:
        - name: initdns
          image: "{{ .Values.imagedns.repository }}:{{ .Values.imagedns.tag }}"
          command: ['sh', '-c', 'until nslookup {{ .Values.serviceHeadless.name }}.{{ .Values.namespace }}.svc.cluster.local; do echo waiting for myservice; sleep 2; done;']
      containers:
        - name: {{ .Values.sensuContainerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh 
            - -ec 
            - |
              echo "== Starting sensu cluster member ${HOST_NAME} in ${INITIAL_LIST}"
                sensu-backend start --etcd-name ${HOST_NAME} \
                  --etcd-initial-cluster ${INITIAL_LIST} \
                  --etcd-initial-advertise-peer-urls http://${HOST_NAME}.{{ .Values.serviceHeadless.name }}.{{ .Values.namespace }}.svc.cluster.local:2380 \
                  --etcd-initial-cluster-token sensu --etcd-initial-cluster-state new \
                  --etcd-advertise-client-urls http://${HOST_NAME}.{{ .Values.serviceHeadless.name }}.{{ .Values.namespace }}.svc.cluster.local:2379 \
                  --etcd-listen-client-urls http://0.0.0.0:2379 --etcd-listen-peer-urls http://0.0.0.0:2380 \
                  --state-dir /var/lib/sensu/sensu-backend/${HOST_NAME} --log-level debug --debug \
                  {{ if .Values.SSLCertificates.enabled }}--trusted-ca-file {{ .Values.SSLCertificates.caCertMountPath }}/sensu-ca.pem --cert-file {{ .Values.SSLCertificates.backendCertMountPath }}/sensu-backend.pem --key-file {{ .Values.SSLCertificates.backendCertMountPath }}/sensu-backend-key.pem --api-url https://{{ .Values.sensuApiUrl }}:{{ .Values.serviceApi.port }} {{ else }}--api-url http://{{ .Values.sensuApiUrl }}:{{ .Values.serviceApi.port }}  {{ end }}
          ports:
          - containerPort: {{ .Values.serviceEtcdClient.port }}
            name: {{ .Values.serviceEtcdClient.name }}
          - containerPort: {{ .Values.serviceEtcdServer.port }}
            name: {{ .Values.serviceEtcdServer.name }}
          - containerPort: {{ .Values.serviceApi.port }}
            name: {{ .Values.serviceApi.name }}
          - containerPort: {{ .Values.serviceWebsocket.port }}
            name: {{ .Values.serviceWebsocket.name }}
          - containerPort: {{ .Values.serviceDashboard.port }}
            name: {{ .Values.serviceDashboard.name }}
          livenessProbe:
            httpGet:
              path: {{ .Values.service.health }}
              port: {{ .Values.serviceApi.port }}
              scheme: {{ if .Values.SSLCertificates.enabled }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: {{ .Values.service.health }}
              port: {{ .Values.serviceApi.port }}
              scheme: {{ if .Values.SSLCertificates.enabled }}HTTPS{{ else }}HTTP{{ end }}
            initialDelaySeconds: 15
          env:
          - name: HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: INITIAL_LIST
            {{- $replicaCount := int .Values.replicaCount }}
            {{- $nodeCount := sub (int .Values.replicaCount ) 1 }}
            {{- $sensuName := .Values.sensuStatefulSetName }}
            {{- $serviceHeadless := .Values.serviceHeadless.name}}
            {{- $namespace := .Values.namespace }}
            value: {{ range $i, $e := until $replicaCount }}{{ $sensuName }}-{{ $e }}=http://{{ $sensuName }}-{{ $e }}.{{ $serviceHeadless }}.{{ $namespace }}.svc.cluster.local:2380{{ if lt $e $nodeCount }},{{ end }}{{end}}
          - name: SENSU_BACKEND_CLUSTER_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.sensuCredentials }}
                key: sensu_backend_cluster_admin_username
          - name: SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.sensuCredentials }} 
                key: sensu_backend_cluster_admin_password
          {{- if .Values.SSLCertificates.enabled }}
          volumeMounts:
          - mountPath: {{ .Values.SSLCertificates.backendCertMountPath }}
            name: {{ .Values.SSLCertificates.backendCertName }}
            readOnly: true
          - mountPath: {{ .Values.SSLCertificates.caCertMountPath }}
            name: {{ .Values.SSLCertificates.caCertName }}
            readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        {{- if .Values.SSLCertificates.enabled }}
        - name: {{ .Values.SSLCertificates.backendVolumeName }}
          secret:
            secretName: {{ .Values.SSLCertificates.backendVolumeSecretName }}
        - name: {{ .Values.SSLCertificates.caVolumeName }}
          secret:
            secretName: {{ .Values.SSLCertificates.caVolumeSecretName }}
        {{- end }}